# Generated by Django 6.0.8 on 2026-09-16 11:08

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="队名")),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, verbose_name="简介"),
                ),
                (
                    "is_recruiting",
                    models.BooleanField(default=True, verbose_name="招募中"),
                ),
                (
                    "disbanded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解散时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="队标",
                    ),
                ),
            ],
            options={
                "verbose_name": "战队",
                "verbose_name_plural": "战队",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_tank", models.BooleanField(default=False, verbose_name="重装")),
                (
                    "role_damage",
                    models.BooleanField(default=False, verbose_name="输出"),
                ),
                (
                    "role_support",
                    models.BooleanField(default=False, verbose_name="支援"),
                ),
                (
                    "message",
                    models.CharField(blank=True, max_length=200, verbose_name="留言"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "decision_note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="拒绝原因"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="teams.team",
                        verbose_name="战队",
                    ),
                ),
            ],
            options={
                "verbose_name": "入队申请",
                "verbose_name_plural": "入队申请",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("captain", "队长"), ("member", "队员")],
                        default="member",
                        max_length=16,
                        verbose_name="身份",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="入队时间"),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="teams.team",
                        verbose_name="战队",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="成员",
                    ),
                ),
            ],
            options={
                "verbose_name": "战队成员",
                "verbose_name_plural": "战队成员",
                "ordering": ["role", "joined_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("disbanded_at__isnull", True)),
                name="unique_active_team_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="teamapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("team", "applicant"),
                name="one_pending_application_per_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                fields=("team", "user"), name="unique_team_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "captain")),
                fields=("team",),
                name="one_captain_per_team",
            ),
        ),
    ]
