# Generated by Django 6.0.8 on 2026-09-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamapplication",
            name="role_tank",
            field=models.BooleanField(default=False, verbose_name="坦克"),
        ),
    ]
