# Generated by Django 6.0.8 on 2026-10-02 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_role_tank_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='recruiting_roles',
            field=models.CharField(blank=True, help_text='位置代码，逗号分隔。', max_length=32, verbose_name='缺的位置'),
        ),
        migrations.CreateModel(
            name='TeamAlumnus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('captain', '队长'), ('member', '队员')], max_length=16, verbose_name='离队时的身份')),
                ('joined_at', models.DateTimeField(verbose_name='入队时间')),
                ('left_at', models.DateTimeField(verbose_name='离队时间')),
                ('reason', models.CharField(choices=[('left', '退出'), ('removed', '被移除')], max_length=16, verbose_name='离队方式')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='teams.team', verbose_name='战队')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_alumni', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '退役成员',
                'verbose_name_plural': '退役成员',
                'ordering': ['-left_at'],
                'constraints': [models.UniqueConstraint(fields=('team', 'user'), name='unique_team_alumnus')],
            },
        ),
    ]
