# Generated by Django 6.0.8 on 2026-10-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_alumni_and_recruiting_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member_contact',
            field=models.CharField(blank=True, help_text='比如队伍 QQ 群号。只有本队成员看得到，入队通过的邮件里也会写上。', max_length=100, verbose_name='队内联系方式'),
        ),
    ]
