# Generated by Django 6.0.8 on 2026-10-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_member_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamapplication',
            name='captain_reminded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提醒队长时间'),
        ),
    ]
