# Generated by Django 6.0.8 on 2026-09-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthProbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=32)),
            ],
            options={
                "verbose_name": "健康检查探针",
                "verbose_name_plural": "健康检查探针",
            },
        ),
    ]
