# Generated by Django 6.0.8 on 2026-09-16 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SMTP 服务器"
                    ),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(default=465, verbose_name="SMTP 端口"),
                ),
                (
                    "smtp_security",
                    models.CharField(
                        choices=[
                            ("none", "无"),
                            ("starttls", "STARTTLS"),
                            ("ssl", "SSL"),
                        ],
                        default="ssl",
                        max_length=16,
                        verbose_name="加密方式",
                    ),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SMTP 账号"
                    ),
                ),
                (
                    "smtp_password",
                    models.TextField(
                        blank=True,
                        help_text="加密存储。后台表单不回显原值，留空表示不修改。",
                        verbose_name="SMTP 密码",
                    ),
                ),
                (
                    "from_address",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="发件地址"
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        default="SJTU 守望先锋社区",
                        max_length=100,
                        verbose_name="发件人名称",
                    ),
                ),
                (
                    "email_subject_prefix",
                    models.CharField(
                        default="[SJTU OW]", max_length=40, verbose_name="邮件主题前缀"
                    ),
                ),
                (
                    "site_description",
                    models.TextField(
                        blank=True, help_text="后续里程碑使用", verbose_name="站点简介"
                    ),
                ),
                (
                    "team_max_members",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="后续里程碑使用",
                        verbose_name="战队人数上限",
                    ),
                ),
                (
                    "team_max_captained",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="后续里程碑使用",
                        verbose_name="每人最多担任队长数",
                    ),
                ),
                (
                    "max_game_accounts",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="后续里程碑使用",
                        verbose_name="每人最多游戏 ID",
                    ),
                ),
                (
                    "lfg_max_active_posts",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="后续里程碑使用",
                        verbose_name="每人最多未过期车帖",
                    ),
                ),
                (
                    "lfg_expire_hours",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="后续里程碑使用",
                        verbose_name="车帖过期小时数",
                    ),
                ),
                (
                    "scrim_reminder_hours",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="后续里程碑使用",
                        verbose_name="内战提前提醒小时数",
                    ),
                ),
                (
                    "moderation_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="后续里程碑使用",
                        verbose_name="启用 AI 内容审核",
                    ),
                ),
                (
                    "moderation_model",
                    models.CharField(
                        default="deepseek-v4.1-flash",
                        help_text="后续里程碑使用",
                        max_length=100,
                        verbose_name="审核模型",
                    ),
                ),
                (
                    "moderation_daily_limit",
                    models.PositiveIntegerField(
                        default=2000,
                        help_text="后续里程碑使用",
                        verbose_name="审核每日调用上限",
                    ),
                ),
                (
                    "moderation_image_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="后续里程碑使用",
                        verbose_name="连图片一起审核",
                    ),
                ),
                (
                    "moderation_high_risk_notify",
                    models.CharField(
                        choices=[("immediate", "立即"), ("daily", "每日汇总")],
                        default="immediate",
                        help_text="后续里程碑使用",
                        max_length=16,
                        verbose_name="高风险内容通知",
                    ),
                ),
                (
                    "font_css_path",
                    models.CharField(
                        blank=True,
                        help_text="后续里程碑使用",
                        max_length=500,
                        verbose_name="字体样式表地址",
                    ),
                ),
                (
                    "font_css_generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="后续里程碑使用",
                        null=True,
                        verbose_name="字体样式表生成时间",
                    ),
                ),
                (
                    "default_share_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="后续里程碑使用",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="默认分享图片",
                    ),
                ),
            ],
            options={
                "verbose_name": "全站设置",
            },
        ),
    ]
