# Generated by Django 6.0.8 on 2026-09-16 06:50

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="max_game_accounts",
            field=models.PositiveIntegerField(
                default=5, verbose_name="每人最多游戏 ID"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="smtp_password",
            field=core.fields.EncryptedTextField(
                blank=True,
                help_text="加密存储。后台表单不回显原值，留空表示不修改。",
                verbose_name="SMTP 密码",
            ),
        ),
    ]
