# Generated by Django 6.0.8 on 2026-09-16 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_profile_and_encrypted_smtp"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="default_share_image",
            field=models.ForeignKey(
                blank=True,
                help_text="没有封面的页面使用这张图作为分享预览。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="默认分享图片",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_description",
            field=models.TextField(
                blank=True,
                help_text="用于页面描述和链接预览。",
                verbose_name="站点简介",
            ),
        ),
    ]
