# Generated by Django 6.0.8 on 2026-09-16 09:22

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_sitesettings_default_share_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="font_css_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="由「设置 → 排版设置」自动生成。",
                null=True,
                verbose_name="字体样式表生成时间",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="font_css_path",
            field=models.CharField(
                blank=True,
                help_text="由「设置 → 排版设置」自动生成。",
                max_length=500,
                verbose_name="字体样式表地址",
            ),
        ),
        migrations.CreateModel(
            name="FontFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="显示名称")),
                (
                    "css_name",
                    models.CharField(
                        help_text="生成样式表时使用，自动分配。",
                        max_length=32,
                        unique=True,
                        verbose_name="样式表字体名",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("upload", "上传"),
                            ("google_fonts", "Google Fonts"),
                            ("url", "网址下载"),
                        ],
                        max_length=16,
                        verbose_name="来源",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        help_text="Google Fonts 字体名称或下载地址。",
                        max_length=500,
                        verbose_name="来源标识",
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("open_source", "开源授权"),
                            ("web_license", "已购买网页嵌入授权"),
                            ("other", "其他"),
                        ],
                        max_length=16,
                        verbose_name="授权类型",
                    ),
                ),
                ("license_note", models.TextField(blank=True, verbose_name="授权说明")),
                (
                    "license_confirmed",
                    models.BooleanField(
                        default=False, verbose_name="已确认允许嵌入网站"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="添加人",
                    ),
                ),
            ],
            options={
                "verbose_name": "字体",
                "verbose_name_plural": "字体",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TypographyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("body", "正文"),
                            ("h1", "一级标题"),
                            ("h2", "二级标题"),
                            ("h3", "三级标题"),
                            ("h4", "四级标题"),
                            ("nav", "导航栏"),
                            ("button", "按钮"),
                            ("numeric", "数字与数据"),
                            ("mono", "游戏 ID 与代码"),
                        ],
                        max_length=16,
                        unique=True,
                        verbose_name="区域",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("system", "系统字体"),
                            ("inherit", "跟随正文"),
                            ("custom", "字体库中的字体"),
                        ],
                        default="inherit",
                        max_length=16,
                        verbose_name="字体来源",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (100, "100 Thin"),
                            (200, "200 ExtraLight"),
                            (300, "300 Light"),
                            (400, "400 Regular"),
                            (500, "500 Medium"),
                            (600, "600 SemiBold"),
                            (700, "700 Bold"),
                            (800, "800 ExtraBold"),
                            (900, "900 Black"),
                        ],
                        default=400,
                        verbose_name="字重",
                    ),
                ),
                (
                    "size_rem",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        verbose_name="字号（rem）",
                    ),
                ),
                (
                    "line_height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="行高（倍）",
                    ),
                ),
                (
                    "letter_spacing_em",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        verbose_name="字间距（em）",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="typography_rules",
                        to="core.fontfamily",
                        verbose_name="字体",
                    ),
                ),
            ],
            options={
                "verbose_name": "排版区域",
                "verbose_name_plural": "排版区域",
            },
        ),
        migrations.CreateModel(
            name="FontFace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (100, "100 Thin"),
                            (200, "200 ExtraLight"),
                            (300, "300 Light"),
                            (400, "400 Regular"),
                            (500, "500 Medium"),
                            (600, "600 SemiBold"),
                            (700, "700 Bold"),
                            (800, "800 ExtraBold"),
                            (900, "900 Black"),
                        ],
                        verbose_name="字重",
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[("normal", "正常"), ("italic", "斜体")],
                        default="normal",
                        max_length=8,
                        verbose_name="样式",
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=core.models.font_original_upload_path,
                        verbose_name="原始文件",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待处理"),
                            ("processing", "处理中"),
                            ("ready", "可用"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="处理进度"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="失败原因")),
                (
                    "slices",
                    models.JSONField(blank=True, default=list, verbose_name="分片"),
                ),
                (
                    "slice_count",
                    models.PositiveIntegerField(default=0, verbose_name="分片数量"),
                ),
                (
                    "total_bytes",
                    models.PositiveIntegerField(default=0, verbose_name="分片总大小"),
                ),
                (
                    "glyph_count",
                    models.PositiveIntegerField(default=0, verbose_name="字符数量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faces",
                        to="core.fontfamily",
                        verbose_name="字体",
                    ),
                ),
            ],
            options={
                "verbose_name": "字重",
                "verbose_name_plural": "字重",
                "ordering": ["family", "weight", "style"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("family", "weight", "style"),
                        name="unique_font_face_per_family",
                    )
                ],
            },
        ),
    ]
