# Generated by Django 6.0.8 on 2026-09-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_fonts"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrerenderedPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="网址路径"
                    ),
                ),
                ("kind", models.CharField(max_length=32, verbose_name="页面类型")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待生成"),
                            ("ready", "已生成"),
                            ("failed", "生成失败"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近一次请求生成"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近一次生成完成"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="内容哈希"
                    ),
                ),
                (
                    "bytes",
                    models.PositiveIntegerField(default=0, verbose_name="未压缩大小"),
                ),
                (
                    "error",
                    models.TextField(blank=True, verbose_name="最近一次失败原因"),
                ),
            ],
            options={
                "verbose_name": "静态页面",
                "verbose_name_plural": "静态页面",
                "ordering": ["path"],
            },
        ),
    ]
