# Generated by Django 6.0.8 on 2026-09-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_prerendered_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=32, unique=True, verbose_name="名称"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="停用后发车时不能选，已有车帖不受影响。",
                        verbose_name="启用",
                    ),
                ),
            ],
            options={
                "verbose_name": "游戏模式",
                "verbose_name_plural": "游戏模式",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
