# Generated by Django 6.0.8 on 2026-09-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_game_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="scrim_reminder_hours",
            field=models.PositiveIntegerField(
                default=2,
                help_text="内战开始前多久给报名者发提醒邮件。",
                verbose_name="内战提前提醒小时数",
            ),
        ),
    ]
