# Generated by Django 6.0.8 on 2026-09-16 15:37

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_sitesettings_scrim_reminder_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="backup_s3_access_key_id",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Access Key ID"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_s3_bucket",
            field=models.CharField(blank=True, max_length=64, verbose_name="存储桶"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_s3_enabled",
            field=models.BooleanField(
                default=False,
                help_text="开启后，每次备份完会加密并上传一份。需要先设好下面几项。",
                verbose_name="备份上传到对象存储",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_s3_endpoint",
            field=models.URLField(
                blank=True,
                help_text="Cloudflare R2 形如 https://<账号ID>.r2.cloudflarestorage.com",
                verbose_name="对象存储地址",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_s3_prefix",
            field=models.CharField(
                blank=True,
                default="sjtu-ow/",
                help_text="存到桶里的哪个目录下。",
                max_length=128,
                verbose_name="路径前缀",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_s3_region",
            field=models.CharField(
                blank=True,
                default="auto",
                help_text="R2 填 auto。",
                max_length=32,
                verbose_name="区域",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="backup_s3_secret_access_key",
            field=core.fields.EncryptedTextField(
                blank=True, help_text="加密存储。", verbose_name="Secret Access Key"
            ),
        ),
    ]
