# Generated by Django 6.0.8 on 2026-09-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_sitesettings_backup_s3_access_key_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="lfg_expire_hours",
            field=models.PositiveIntegerField(
                default=2,
                help_text="车帖在开车时间之后多少小时过期。",
                verbose_name="车帖过期小时数",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="lfg_max_active_posts",
            field=models.PositiveIntegerField(
                default=3,
                help_text="每人同时最多有几个没过期的车帖。",
                verbose_name="每人最多未过期车帖",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="moderation_daily_limit",
            field=models.PositiveIntegerField(
                default=2000,
                help_text="每天最多调用多少次审核接口，超出的内容记为「无法判定」转人工。",
                verbose_name="审核每日调用上限",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="moderation_enabled",
            field=models.BooleanField(
                default=True,
                help_text="关掉后新内容不再送审。没有配置 MODERATION_API_KEY 时本来就不送审。",
                verbose_name="启用 AI 内容审核",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="moderation_high_risk_notify",
            field=models.CharField(
                choices=[("immediate", "立即"), ("daily", "每日汇总")],
                default="immediate",
                help_text="AI 判为高风险的内容什么时候邮件通知管理员。",
                max_length=16,
                verbose_name="高风险内容通知",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="moderation_image_enabled",
            field=models.BooleanField(
                default=False,
                help_text="开启后投稿里的图片也送审，费用更高。",
                verbose_name="连图片一起审核",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="moderation_model",
            field=models.CharField(
                default="deepseek-v4.1-flash",
                help_text="服务商接口里的模型名。",
                max_length=100,
                verbose_name="审核模型",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="team_max_captained",
            field=models.PositiveIntegerField(
                default=3,
                help_text="每人最多同时担任几支战队的队长。",
                verbose_name="每人最多担任队长数",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="team_max_members",
            field=models.PositiveIntegerField(
                default=10,
                help_text="一支战队最多多少人，含队长。",
                verbose_name="战队人数上限",
            ),
        ),
    ]
