# Generated by Django 6.0.8 on 2026-09-19 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_settings_help_text"),
    ]

    operations = [
        # Round 066 removed the lfg app. Its table has a foreign key to
        # GameMode, so it goes first; IF EXISTS because fresh databases never
        # had it. Its migration records go too, so the name is free again.
        migrations.RunSQL(
            "DROP TABLE IF EXISTS lfg_lfgpost", reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "DELETE FROM django_migrations WHERE app = 'lfg'",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.DeleteModel(
            name="GameMode",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="lfg_expire_hours",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="lfg_max_active_posts",
        ),
    ]
