# Generated by Django 6.0.8 on 2026-09-26 07:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_lfg"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="founded_on",
            field=models.DateField(
                blank=True,
                help_text="首页「社区已成立 N 年 M 天」按它算；空着首页不显示这一项。",
                null=True,
                verbose_name="社区成立日期",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="qq_group_url",
            field=models.URLField(
                blank=True,
                help_text="QQ 群的分享链接，https:// 开头。首页「加入 QQ 群」链接到这里；空着不显示。",
                validators=[core.models.https_only],
                verbose_name="QQ 群链接",
            ),
        ),
    ]
