# Generated by Django 6.0.8 on 2026-09-26 13:17

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_sitesettings_founded_on_sitesettings_qq_group_url"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="首页最上面的大图，建议 2400×1000 以上；空着时显示深色底和校徽。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="首屏图片",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="founded_on",
            field=models.DateField(
                blank=True,
                help_text="首页数字条「社区已成立 N 年 M 天」按它算；空着不显示这一项。",
                null=True,
                verbose_name="社区成立日期",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="qq_group_url",
            field=models.URLField(
                blank=True,
                help_text="QQ 群的分享链接，https:// 开头。首页首屏的「加入 QQ 群」按钮链接到这里；空着不显示。",
                validators=[core.models.https_only],
                verbose_name="QQ 群链接",
            ),
        ),
    ]
