# Generated by Django 6.0.8 on 2026-10-02 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_hero_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banner_members',
            field=models.ForeignKey(blank=True, help_text='栏目页顶部标题区背后的图（设计 13.2.5），按浅色或深色模式压一层白色或深色。建议 2400×640 以上，可以用守望先锋官方图。空着用本站的占位插画。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='「成员」栏目横幅'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_news',
            field=models.ForeignKey(blank=True, help_text='栏目页顶部标题区背后的图（设计 13.2.5），按浅色或深色模式压一层白色或深色。建议 2400×640 以上，可以用守望先锋官方图。空着用本站的占位插画。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='「资讯」栏目横幅'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_scrims',
            field=models.ForeignKey(blank=True, help_text='栏目页顶部标题区背后的图（设计 13.2.5），按浅色或深色模式压一层白色或深色。建议 2400×640 以上，可以用守望先锋官方图。空着用本站的占位插画。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='「内战」栏目横幅'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_teams',
            field=models.ForeignKey(blank=True, help_text='栏目页顶部标题区背后的图（设计 13.2.5），按浅色或深色模式压一层白色或深色。建议 2400×640 以上，可以用守望先锋官方图。空着用本站的占位插画。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='「战队」栏目横幅'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_tournaments',
            field=models.ForeignKey(blank=True, help_text='栏目页顶部标题区背后的图（设计 13.2.5），按浅色或深色模式压一层白色或深色。建议 2400×640 以上，可以用守望先锋官方图。空着用本站的占位插画。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='「赛事」栏目横幅'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='首页首屏背后的图（按浅色或深色模式压一层白色或深色，右半边是交大校徽），建议 2400×1350 以上，可以用守望先锋官方图。空着用本站的占位插画。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='首屏图片'),
        ),
    ]
