# Generated by Django 6.0.8 on 2026-10-03 12:07

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesettings_section_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='backup_s3_access_key_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='访问密钥 ID（Access Key ID）'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='backup_s3_secret_access_key',
            field=core.fields.EncryptedTextField(blank=True, help_text='加密存储。', verbose_name='密钥（Secret Access Key）'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='moderation_daily_limit',
            field=models.PositiveIntegerField(default=2000, help_text='每天最多调用多少次审核接口，超出的排到第二天再审（5.5.3）。', verbose_name='审核每日调用上限'),
        ),
    ]
