# Generated by Django 6.0.8 on 2026-10-03 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_settings_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tournament', '新赛事'), ('scrim', '新内战')], max_length=16, verbose_name='类型')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象 ID')),
                ('subject', models.CharField(max_length=200, verbose_name='主题')),
                ('recipient_count', models.PositiveIntegerField(default=0, verbose_name='收信人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '活动通知',
                'verbose_name_plural': '活动通知',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'object_id'), name='core_broadcast_once')],
            },
        ),
    ]
