# Generated by Django 6.0.8 on 2026-10-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_broadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='kind',
            field=models.CharField(choices=[('tournament', '新赛事'), ('scrim', '新内战'), ('article', '新文章')], max_length=16, verbose_name='类型'),
        ),
    ]
