# Generated by Django 6.0.8 on 2026-10-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_broadcast_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tournament_reminder_hours',
            field=models.PositiveIntegerField(default=24, help_text='填了比赛时间的赛事，开始前多久给已通过报名的队员发提醒邮件。', verbose_name='赛事提前提醒小时数'),
        ),
    ]
