# Generated by Django 6.0.8 on 2026-10-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_tournament_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="waits_for_publish",
            field=models.BooleanField(default=False, verbose_name="等上线后发"),
        ),
    ]
