# Generated by Django 6.0.8 on 2026-10-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_broadcast_waits_for_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='moderation_high_risk_notify',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='moderation_alert_email',
            field=models.EmailField(blank=True, help_text='AI 每 30 分钟巡查一次，发现可能不妥的内容就给这个邮箱发信。空着就发给所有超级管理员。', max_length=254, verbose_name='巡查提醒发到'),
        ),
    ]
