# Generated by Django 6.0.8 on 2026-10-05 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_ai_settings_in_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='broadcast',
            name='core_broadcast_once',
        ),
        migrations.AddField(
            model_name='broadcast',
            name='audience',
            field=models.CharField(choices=[('everyone', '全体成员'), ('participants', '报名的人')], default='everyone', max_length=16, verbose_name='发给'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='before',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='之前发过'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='moved_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='原来的时间'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='note',
            field=models.TextField(blank=True, verbose_name='说明'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['kind', 'object_id'], name='core_broadc_kind_e71785_idx'),
        ),
    ]
