# Generated by Django 6.0.8 on 2026-10-05 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_manual_notices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeldLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.UUIDField(db_index=True, verbose_name='哪件事')),
                ('letter', models.JSONField(verbose_name='信')),
                ('recipients', models.JSONField(verbose_name='收信人')),
                ('back', models.CharField(blank=True, max_length=500, verbose_name='回到')),
                ('in_back_office', models.BooleanField(default=False, verbose_name='在后台')),
                ('state', models.CharField(choices=[('waiting', '等着'), ('sent', '发了'), ('skipped', '没发')], default='waiting', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='决定时间')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='做事的人')),
            ],
            options={
                'verbose_name': '待发的信',
                'verbose_name_plural': '待发的信',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
