# Generated by Django 6.0.8 on 2026-09-25 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0004_article_comments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=500, verbose_name="内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="编辑时间"
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False, verbose_name="置顶")),
                (
                    "is_hidden",
                    models.BooleanField(default=False, verbose_name="已隐藏"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="作者已删除"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="赞数"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="content.articlepage",
                        verbose_name="文章",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="只指向顶层评论；回复的回复仍挂在同一条顶层评论下。",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comments.comment",
                        verbose_name="所属顶层评论",
                    ),
                ),
                (
                    "reply_to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="回复谁",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["page", "created_at"],
                        name="comments_co_page_id_afc659_idx",
                    ),
                    models.Index(
                        fields=["page", "is_pinned", "like_count"],
                        name="comments_co_page_id_a9bf6e_idx",
                    ),
                ],
            },
        ),
    ]
