# Generated by Django 6.0.8 on 2026-09-16 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                (
                    "summary",
                    models.CharField(blank=True, max_length=300, verbose_name="简介"),
                ),
                ("description", models.TextField(blank=True, verbose_name="详细说明")),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="比赛时间"
                    ),
                ),
                (
                    "registration_opens_at",
                    models.DateTimeField(verbose_name="报名开始时间"),
                ),
                (
                    "registration_closes_at",
                    models.DateTimeField(verbose_name="报名截止时间"),
                ),
                (
                    "roster_min",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="参赛人数下限"
                    ),
                ),
                (
                    "roster_max",
                    models.PositiveSmallIntegerField(
                        default=6, verbose_name="参赛人数上限"
                    ),
                ),
                (
                    "sjtu_only",
                    models.BooleanField(default=False, verbose_name="仅限交大"),
                ),
                (
                    "review_mode",
                    models.CharField(
                        choices=[
                            ("local", "本站审核"),
                            ("upstream", "上游审核"),
                            ("two_stage", "两级审核"),
                        ],
                        default="local",
                        max_length=16,
                        verbose_name="审核模式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("finished", "已结束"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="上游赛事 ID"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="首次发布时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="封面",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "赛事",
                "verbose_name_plural": "赛事",
                "ordering": ["-registration_opens_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("roster_min__gte", 1),
                            ("roster_max__lte", 20),
                            ("roster_min__lte", models.F("roster_max")),
                        ),
                        name="tournament_roster_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "registration_opens_at__lt",
                                models.F("registration_closes_at"),
                            )
                        ),
                        name="tournament_registration_window",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("external_id", ""), _negated=True),
                        fields=("external_id",),
                        name="tournament_external_id_unique",
                    ),
                ],
            },
        ),
    ]
