# Generated by Django 6.0.8 on 2026-09-16 12:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="详细说明"),
        ),
    ]
