# Generated by Django 6.0.8 on 2026-09-16 12:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_and_encrypted_smtp"),
        ("teams", "0001_initial"),
        ("tournaments", "0002_alter_tournament_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("awaiting_upstream", "待上游确认"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="pending",
                        max_length=24,
                        verbose_name="状态",
                    ),
                ),
                (
                    "team_name",
                    models.CharField(max_length=16, verbose_name="战队名称快照"),
                ),
                (
                    "roster_version",
                    models.PositiveIntegerField(default=1, verbose_name="名单版本"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="提交时间"
                    ),
                ),
                (
                    "status_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="最近一次审核备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交人",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="teams.team",
                        verbose_name="战队",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="tournaments.tournament",
                        verbose_name="赛事",
                    ),
                ),
            ],
            options={
                "verbose_name": "报名",
                "verbose_name_plural": "报名",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=16, verbose_name="昵称快照")),
                (
                    "battletag",
                    models.CharField(max_length=64, verbose_name="游戏 ID 快照"),
                ),
                (
                    "is_sjtu",
                    models.BooleanField(default=False, verbose_name="是否交大"),
                ),
                (
                    "rank_tank",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="坦克段位"
                    ),
                ),
                (
                    "rank_damage",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="输出段位"
                    ),
                ),
                (
                    "rank_support",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="支援段位"
                    ),
                ),
                (
                    "is_captain",
                    models.BooleanField(default=False, verbose_name="是否队长"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="占名额")),
                (
                    "game_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.gameaccount",
                        verbose_name="游戏 ID",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="tournaments.registration",
                        verbose_name="报名",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_members",
                        to="tournaments.tournament",
                        verbose_name="赛事",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="队员",
                    ),
                ),
            ],
            options={
                "verbose_name": "名单成员",
                "verbose_name_plural": "名单成员",
                "ordering": ["-is_captain", "nickname"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "提交报名"),
                            ("resubmit", "重新提交"),
                            ("sync_roster", "同步名单"),
                            ("approve", "通过"),
                            ("reject", "驳回"),
                            ("revoke", "撤销通过"),
                            ("withdraw", "撤回"),
                        ],
                        max_length=16,
                        verbose_name="操作",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "待审核"),
                            ("awaiting_upstream", "待上游确认"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                            ("withdrawn", "已撤回"),
                        ],
                        max_length=24,
                        verbose_name="变化前状态",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("awaiting_upstream", "待上游确认"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                            ("withdrawn", "已撤回"),
                        ],
                        max_length=24,
                        verbose_name="变化后状态",
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("captain", "队长"),
                            ("admin", "本站管理员"),
                            ("upstream", "上游"),
                            ("system", "系统"),
                        ],
                        max_length=16,
                        verbose_name="操作方",
                    ),
                ),
                (
                    "roster_version",
                    models.PositiveIntegerField(default=1, verbose_name="名单版本"),
                ),
                (
                    "roster_snapshot",
                    models.JSONField(blank=True, null=True, verbose_name="名单快照"),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="tournaments.registration",
                        verbose_name="报名",
                    ),
                ),
            ],
            options={
                "verbose_name": "报名状态日志",
                "verbose_name_plural": "报名状态日志",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["tournament", "status"], name="tournaments_tournam_c14717_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["updated_at", "id"], name="tournaments_updated_5b45e3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("tournament", "team"), name="unique_registration_per_team"
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("tournament", "user"),
                name="one_active_roster_per_user_per_tournament",
            ),
        ),
    ]
