# Generated by Django 6.0.8 on 2026-09-16 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
        ("tournaments", "0003_registration_registrationmember_and_more"),
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tournament",
            name="tournament_external_id_unique",
        ),
        migrations.AddField(
            model_name="registrationstatuslog",
            name="actor_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="integrations.apiclient",
                verbose_name="操作的上游",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="source_client",
            field=models.ForeignKey(
                blank=True,
                help_text="为空表示本站创建。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments",
                to="integrations.apiclient",
                verbose_name="推送来源",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("source_client", "external_id"),
                name="tournament_external_id_unique",
            ),
        ),
    ]
