# Generated by Django 6.0.8 on 2026-09-25 15:37

from django.db import migrations, models


def awaiting_upstream_becomes_pending(apps, schema_editor):
    """Round 067: nobody will ever confirm these, so they go back to review.

    Only the live status is mapped. Status log rows are append-only history
    (design 12.8.4) and keep whatever values they were written with.
    """
    Registration = apps.get_model("tournaments", "Registration")
    Registration.objects.filter(status="awaiting_upstream").update(status="pending")


class Migration(migrations.Migration):

    dependencies = [
        (
            "tournaments",
            "0004_remove_tournament_tournament_external_id_unique_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            awaiting_upstream_becomes_pending, migrations.RunPython.noop
        ),
        migrations.RemoveConstraint(
            model_name="tournament",
            name="tournament_external_id_unique",
        ),
        migrations.RemoveField(
            model_name="registrationstatuslog",
            name="actor_client",
        ),
        migrations.AddField(
            model_name="tournament",
            name="auto_approve",
            field=models.BooleanField(
                default=False,
                help_text="打开后，报名通过全部校验即由系统自动通过，不需要管理员审核。已经有报名之后不能再改。",
                verbose_name="报名自动通过",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("approved", "已通过"),
                    ("rejected", "已驳回"),
                    ("withdrawn", "已撤回"),
                ],
                default="pending",
                max_length=24,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="registrationstatuslog",
            name="actor_type",
            field=models.CharField(
                choices=[
                    ("captain", "队长"),
                    ("admin", "本站管理员"),
                    ("system", "系统"),
                ],
                max_length=16,
                verbose_name="操作方",
            ),
        ),
        migrations.AlterField(
            model_name="registrationstatuslog",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "待审核"),
                    ("approved", "已通过"),
                    ("rejected", "已驳回"),
                    ("withdrawn", "已撤回"),
                ],
                max_length=24,
                verbose_name="变化前状态",
            ),
        ),
        migrations.AlterField(
            model_name="registrationstatuslog",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("approved", "已通过"),
                    ("rejected", "已驳回"),
                    ("withdrawn", "已撤回"),
                ],
                max_length=24,
                verbose_name="变化后状态",
            ),
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="review_mode",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="source_client",
        ),
    ]
