# Generated by Django 6.0.8 on 2026-09-25 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_lfg"),
        ("tournaments", "0005_remove_upstream"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="allow_individual_signup",
            field=models.BooleanField(
                default=False,
                help_text="打开后，没有战队的用户可以个人报名，由赛事管理员编成临时队伍（设计 8.8）。",
                verbose_name="开放个人报名",
            ),
        ),
        migrations.CreateModel(
            name="IndividualSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_tank", models.BooleanField(default=False, verbose_name="坦克")),
                (
                    "role_damage",
                    models.BooleanField(default=False, verbose_name="输出"),
                ),
                (
                    "role_support",
                    models.BooleanField(default=False, verbose_name="支援"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="报名时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "game_account",
                    models.ForeignKey(
                        help_text="设计 3.5.2：未结束赛事的个人报名拦住删除。",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="individual_signups",
                        to="accounts.gameaccount",
                        verbose_name="游戏 ID",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="individual_signups",
                        to="tournaments.registration",
                        verbose_name="编入的队伍",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_signups",
                        to="tournaments.tournament",
                        verbose_name="赛事",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_signups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "个人报名",
                "verbose_name_plural": "个人报名",
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tournament", "user"),
                        name="individual_signup_unique_per_user",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("role_tank", True),
                            ("role_damage", True),
                            ("role_support", True),
                            _connector="OR",
                        ),
                        name="individual_signup_needs_a_role",
                    ),
                ],
            },
        ),
    ]
