# Generated by Django 6.0.8 on 2026-09-25 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        ("tournaments", "0006_individual_signup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="为空表示临时队伍（设计 8.8.2）。",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                to="teams.team",
                verbose_name="战队",
            ),
        ),
        migrations.AlterField(
            model_name="registrationstatuslog",
            name="action",
            field=models.CharField(
                choices=[
                    ("submit", "提交报名"),
                    ("resubmit", "重新提交"),
                    ("sync_roster", "同步名单"),
                    ("approve", "通过"),
                    ("reject", "驳回"),
                    ("revoke", "撤销通过"),
                    ("withdraw", "撤回"),
                    ("form_team", "编队"),
                    ("member_left", "退出队伍"),
                    ("dissolve", "解散队伍"),
                ],
                max_length=16,
                verbose_name="操作",
            ),
        ),
        migrations.AlterField(
            model_name="registrationstatuslog",
            name="actor_type",
            field=models.CharField(
                choices=[
                    ("captain", "队长"),
                    ("admin", "本站管理员"),
                    ("system", "系统"),
                    ("member", "队员"),
                ],
                max_length=16,
                verbose_name="操作方",
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.CheckConstraint(
                condition=models.Q(("team_name", ""), _negated=True),
                name="registration_has_a_name",
            ),
        ),
    ]
