# Generated by Django 6.0.8 on 2026-10-02 17:47

from django.db import migrations, models


def flag_to_mode(apps, schema_editor):
    """Design 8.1 (v5.3): a tournament that took individuals keeps taking them;
    one that did not stays a team tournament, as it was."""
    Tournament = apps.get_model("tournaments", "Tournament")
    Tournament.objects.filter(allow_individual_signup=True).update(
        registration_mode="individual"
    )
    Tournament.objects.filter(allow_individual_signup=False).update(
        registration_mode="team"
    )


def mode_to_flag(apps, schema_editor):
    Tournament = apps.get_model("tournaments", "Tournament")
    Tournament.objects.update(allow_individual_signup=False)
    Tournament.objects.filter(registration_mode="individual").update(
        allow_individual_signup=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0007_adhoc_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="registration_mode",
            field=models.CharField(
                choices=[("individual", "个人报名"), ("team", "整队报名")],
                default="individual",
                help_text="个人报名：每个人自己报名（队长也一样），由赛事管理员编成临时队伍。整队报名：只收战队，队长报名后全队直接进入名单，不需要队员确认。已经有人报名之后不能再改。",
                max_length=16,
                verbose_name="报名方式",
            ),
        ),
        migrations.RunPython(flag_to_mode, mode_to_flag),
        migrations.RemoveField(
            model_name="tournament",
            name="allow_individual_signup",
        ),
        migrations.AlterField(
            model_name="tournament",
            name="auto_approve",
            field=models.BooleanField(
                default=False,
                help_text="只对整队报名有效（临时队伍编成即通过）。打开后，报名通过全部校验即由系统自动通过，不需要管理员审核。已经有报名之后不能再改。",
                verbose_name="报名自动通过",
            ),
        ),
    ]
