# Generated by Django 6.0.8 on 2026-10-03 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_avatar_submission'),
        ('tournaments', '0008_registration_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualsignup',
            name='game_account',
            field=models.ForeignKey(blank=True, help_text='设计 3.5.2：未结束赛事的个人报名拦住删除；赛事结束或取消后可以删，这里置空（115 轮，原来是 PROTECT，删了会出错）。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_signups', to='accounts.gameaccount', verbose_name='游戏 ID'),
        ),
    ]
