# Generated by Django 6.0.8 on 2026-10-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_individual_signup_game_account_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提醒发送时间'),
        ),
    ]
