# Generated by Django 6.0.8 on 2026-10-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_tournament_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='participant_contact',
            field=models.CharField(blank=True, help_text='比如选手 QQ 群号。只有报了这项赛事的人看得到（有效名单里的人、个人报名过的人），也会写进报名通过、编队和开赛提醒的邮件。不要写进上面公开的详细说明。', max_length=100, verbose_name='选手联系方式'),
        ),
    ]
