# Generated by Django 6.0.8 on 2026-10-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_markdown_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='moved_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='报名的人原来知道的时间'),
        ),
    ]
