# Generated by Django 6.0.8 on 2026-10-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_manual_notices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_opens_at',
            field=models.DateTimeField(null=True, verbose_name='报名开始时间'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_closes_at',
            field=models.DateTimeField(null=True, verbose_name='报名截止时间'),
        ),
    ]
