# Generated by Django 6.0.8 on 2026-09-16 06:50

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("qq", "QQ"),
                            ("wechat", "微信"),
                            ("phone", "手机号"),
                            ("other", "其他"),
                        ],
                        max_length=16,
                        verbose_name="类型",
                    ),
                ),
                ("value", models.CharField(max_length=64, verbose_name="内容")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_methods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "联系方式",
                "verbose_name_plural": "联系方式",
                "constraints": [
                    models.UniqueConstraint(
                        models.F("user"),
                        models.F("type"),
                        name="accounts_contactmethod_user_type_unique",
                        violation_error_message="每种联系方式只能填写一次。",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FeatureGroupRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("lfg_post", "在组队大厅发车"),
                            ("team_create", "创建战队"),
                            ("team_apply", "申请加入战队"),
                            ("tournament_register", "报名赛事"),
                            ("scrim_signup", "报名内战"),
                            ("article_submit", "投稿"),
                        ],
                        max_length=32,
                        verbose_name="功能",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="原因"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_restrictions",
                        to="auth.group",
                        verbose_name="用户组",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feature_group_restriction_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户组功能限制",
                "verbose_name_plural": "用户组功能限制",
                "constraints": [
                    models.UniqueConstraint(
                        models.F("group"),
                        models.F("feature"),
                        name="accounts_featuregrouprestriction_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FeatureUserRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("lfg_post", "在组队大厅发车"),
                            ("team_create", "创建战队"),
                            ("team_apply", "申请加入战队"),
                            ("tournament_register", "报名赛事"),
                            ("scrim_signup", "报名内战"),
                            ("article_submit", "投稿"),
                        ],
                        max_length=32,
                        verbose_name="功能",
                    ),
                ),
                (
                    "allowed",
                    models.BooleanField(default=False, verbose_name="单独允许"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="原因"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feature_user_rule_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户功能规则",
                "verbose_name_plural": "用户功能规则",
                "constraints": [
                    models.UniqueConstraint(
                        models.F("user"),
                        models.F("feature"),
                        name="accounts_featureuserrule_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GameAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("battletag", models.CharField(max_length=64, verbose_name="游戏 ID")),
                (
                    "rank_tank",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="坦克段位"
                    ),
                ),
                (
                    "rank_damage",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="输出段位"
                    ),
                ),
                (
                    "rank_support",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="支援段位"
                    ),
                ),
                (
                    "ranks_updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="段位更新时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "游戏 ID",
                "verbose_name_plural": "游戏 ID",
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("battletag"),
                        name="accounts_gameaccount_battletag_ci_unique",
                        violation_error_message="该游戏 ID 已被其他账号绑定，如有疑问请联系管理员",
                    )
                ],
            },
        ),
    ]
