# Generated by Django 6.0.8 on 2026-09-19 05:00

from django.db import migrations, models


def forget_lfg_rules(apps, schema_editor):
    """Round 066: the lfg_post feature no longer exists."""
    for name in ("FeatureUserRule", "FeatureGroupRestriction"):
        apps.get_model("accounts", name).objects.filter(feature="lfg_post").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_and_encrypted_smtp"),
    ]

    operations = [
        migrations.RunPython(forget_lfg_rules, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="featuregrouprestriction",
            name="feature",
            field=models.CharField(
                choices=[
                    ("team_create", "创建战队"),
                    ("team_apply", "申请加入战队"),
                    ("tournament_register", "报名赛事"),
                    ("scrim_signup", "报名内战"),
                    ("article_submit", "投稿"),
                ],
                max_length=32,
                verbose_name="功能",
            ),
        ),
        migrations.AlterField(
            model_name="featureuserrule",
            name="feature",
            field=models.CharField(
                choices=[
                    ("team_create", "创建战队"),
                    ("team_apply", "申请加入战队"),
                    ("tournament_register", "报名赛事"),
                    ("scrim_signup", "报名内战"),
                    ("article_submit", "投稿"),
                ],
                max_length=32,
                verbose_name="功能",
            ),
        ),
    ]
