# Generated by Django 6.0.8 on 2026-09-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_lfg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuregrouprestriction",
            name="feature",
            field=models.CharField(
                choices=[
                    ("team_create", "创建战队"),
                    ("team_apply", "申请加入战队"),
                    ("tournament_register", "报名赛事"),
                    ("scrim_signup", "报名内战"),
                    ("article_submit", "投稿"),
                    ("article_comment", "评论文章"),
                ],
                max_length=32,
                verbose_name="功能",
            ),
        ),
        migrations.AlterField(
            model_name="featureuserrule",
            name="feature",
            field=models.CharField(
                choices=[
                    ("team_create", "创建战队"),
                    ("team_apply", "申请加入战队"),
                    ("tournament_register", "报名赛事"),
                    ("scrim_signup", "报名内战"),
                    ("article_submit", "投稿"),
                    ("article_comment", "评论文章"),
                ],
                max_length=32,
                verbose_name="功能",
            ),
        ),
    ]
