# Generated by Django 6.0.8 on 2026-10-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_article_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flex_roles',
            field=models.CharField(blank=True, help_text='位置代码，逗号分隔。', max_length=32, verbose_name='也能打'),
        ),
        migrations.AddField(
            model_name='user',
            name='main_role',
            field=models.CharField(blank=True, choices=[('tank', '坦克'), ('damage', '输出'), ('support', '支援')], max_length=8, verbose_name='主位置'),
        ),
        migrations.AddField(
            model_name='user',
            name='motto',
            field=models.CharField(blank=True, max_length=30, verbose_name='个人宣言'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_rank',
            field=models.BooleanField(default=True, help_text='在成员展示和战队主页显示各位置的最高段位。', verbose_name='公开段位'),
        ),
    ]
