# Generated by Django 6.0.8 on 2026-10-03 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_avatar'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuregrouprestriction',
            name='feature',
            field=models.CharField(choices=[('team_create', '创建战队'), ('team_apply', '申请加入战队'), ('tournament_register', '报名赛事'), ('scrim_signup', '报名内战'), ('article_submit', '投稿'), ('article_comment', '评论文章'), ('avatar_upload', '上传头像')], max_length=32, verbose_name='功能'),
        ),
        migrations.AlterField(
            model_name='featureuserrule',
            name='feature',
            field=models.CharField(choices=[('team_create', '创建战队'), ('team_apply', '申请加入战队'), ('tournament_register', '报名赛事'), ('scrim_signup', '报名内战'), ('article_submit', '投稿'), ('article_comment', '评论文章'), ('avatar_upload', '上传头像')], max_length=32, verbose_name='功能'),
        ),
        migrations.CreateModel(
            name='AvatarSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '未通过'), ('withdrawn', '已撤回'), ('taken_down', '已撤下')], default='pending', max_length=16, verbose_name='状态')),
                ('reason', models.CharField(blank=True, choices=[('illegal', '违法违规'), ('porn', '色情低俗'), ('attack', '人身攻击'), ('politics', '政治敏感'), ('scam', '广告与诈骗'), ('game_trade', '游戏违规交易'), ('privacy', '泄露他人隐私'), ('impersonation', '冒充官方'), ('other', '其他可疑')], max_length=32, verbose_name='原因')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='图片')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_submissions', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '头像上传',
                'verbose_name_plural': '头像上传',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(models.F('user'), condition=models.Q(('status', 'pending')), name='accounts_avatarsubmission_one_pending')],
            },
        ),
    ]
