# Generated by Django 6.0.8 on 2026-10-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_avatar_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepts_announcements',
            field=models.BooleanField(default=True, help_text='新赛事、新内战发布时的群发邮件（设计 10.4）。和本人有关的通知不受影响。', verbose_name='接收活动通知'),
        ),
    ]
