# Generated by Django 6.0.8 on 2026-10-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_faces_go_live"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="calendar_version",
            field=models.PositiveIntegerField(
                default=0, verbose_name="日历订阅地址版本"
            ),
        ),
    ]
