# Generated by Django 6.0.8 on 2026-09-16 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_profile_and_encrypted_smtp"),
        ("core", "0007_game_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LfgPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_tank",
                    models.BooleanField(default=False, verbose_name="缺重装"),
                ),
                (
                    "role_damage",
                    models.BooleanField(default=False, verbose_name="缺输出"),
                ),
                (
                    "role_support",
                    models.BooleanField(default=False, verbose_name="缺支援"),
                ),
                ("start_at", models.DateTimeField(verbose_name="开车时间")),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "招人中"),
                            ("full", "已满"),
                            ("closed", "已关闭"),
                        ],
                        default="open",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "game_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lfg_posts",
                        to="accounts.gameaccount",
                        verbose_name="游戏 ID",
                    ),
                ),
                (
                    "mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lfg_posts",
                        to="core.gamemode",
                        verbose_name="模式",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lfg_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="车主",
                    ),
                ),
            ],
            options={
                "verbose_name": "车帖",
                "verbose_name_plural": "车帖",
                "ordering": ["start_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["expires_at", "status"],
                        name="lfg_lfgpost_expires_4517c2_idx",
                    )
                ],
            },
        ),
    ]
