# Generated by Django 6.0.8 on 2026-09-16 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_profile_and_encrypted_smtp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scrim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                ("starts_at", models.DateTimeField(verbose_name="开始时间")),
                (
                    "signup_closes_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="留空表示开始前都可以报名。",
                        null=True,
                        verbose_name="报名截止时间",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("rq_5v5", "角色限定 5v5"),
                            ("rq_6v6", "角色限定 6v6"),
                            ("open_5v5", "不限位置 5v5"),
                            ("open_6v6", "不限位置 6v6"),
                        ],
                        default="rq_5v5",
                        max_length=16,
                        verbose_name="规格",
                    ),
                ),
                (
                    "sjtu_only",
                    models.BooleanField(default=False, verbose_name="仅限交大"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("finished", "已结束"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "teams_generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="分队时间"
                    ),
                ),
                (
                    "roster_changed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="名单变动时间"
                    ),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提醒发送时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scrims_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "内战活动",
                "verbose_name_plural": "内战活动",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrimSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_tank", models.BooleanField(default=False, verbose_name="坦克")),
                (
                    "role_damage",
                    models.BooleanField(default=False, verbose_name="输出"),
                ),
                (
                    "role_support",
                    models.BooleanField(default=False, verbose_name="支援"),
                ),
                (
                    "is_selected",
                    models.BooleanField(default=False, verbose_name="上场"),
                ),
                (
                    "team",
                    models.CharField(
                        blank=True,
                        choices=[("a", "A 队"), ("b", "B 队")],
                        default="",
                        max_length=1,
                        verbose_name="队伍",
                    ),
                ),
                (
                    "assigned_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tank", "坦克"),
                            ("damage", "输出"),
                            ("support", "支援"),
                        ],
                        default="",
                        max_length=8,
                        verbose_name="分到的位置",
                    ),
                ),
                (
                    "rating_used",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="分队使用的段位分数"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="报名时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "game_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scrim_signups",
                        to="accounts.gameaccount",
                        verbose_name="游戏 ID",
                    ),
                ),
                (
                    "scrim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signups",
                        to="scrims.scrim",
                        verbose_name="内战活动",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrim_signups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="玩家",
                    ),
                ),
            ],
            options={
                "verbose_name": "内战报名",
                "verbose_name_plural": "内战报名",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="scrim",
            index=models.Index(
                fields=["status", "starts_at"], name="scrims_scri_status_1cb3cc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="scrimsignup",
            constraint=models.UniqueConstraint(
                fields=("scrim", "user"), name="scrim_signup_unique_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="scrimsignup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("role_tank", True),
                    ("role_damage", True),
                    ("role_support", True),
                    _connector="OR",
                ),
                name="scrim_signup_needs_a_role",
            ),
        ),
    ]
