# Generated by Django 6.0.8 on 2026-09-25 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_lfg"),
        ("scrims", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrimsignup",
            name="game_account",
            field=models.ForeignKey(
                blank=True,
                help_text="设计 3.5.2：只有未结束的内战拦住删除；删了之后这里置空。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scrim_signups",
                to="accounts.gameaccount",
                verbose_name="游戏 ID",
            ),
        ),
    ]
