# Generated by Django 6.0.8 on 2026-10-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrims', '0002_game_account_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrim',
            name='moved_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='报名的人原来知道的时间'),
        ),
    ]
