# Generated by Django 6.0.8 on 2026-10-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrims', '0003_manual_notices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrim',
            name='starts_at',
            field=models.DateTimeField(null=True, verbose_name='开始时间'),
        ),
    ]
