# Generated by Django 6.0.8 on 2026-09-16 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="日期")),
                (
                    "calls",
                    models.PositiveIntegerField(default=0, verbose_name="调用次数"),
                ),
                (
                    "items",
                    models.PositiveIntegerField(default=0, verbose_name="送审条数"),
                ),
                (
                    "input_tokens",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="输入 token"
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="输出 token"
                    ),
                ),
            ],
            options={
                "verbose_name": "审核用量",
                "verbose_name_plural": "审核用量",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ModerationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("nickname", "昵称"),
                            ("team_name", "队名"),
                            ("team_description", "战队简介"),
                            ("lfg_note", "车帖备注"),
                            ("application_message", "入队申请留言"),
                            ("article", "文章 / 稿件"),
                            ("tournament_description", "赛事说明"),
                            ("scrim_description", "内战说明"),
                            ("page", "普通页面"),
                            ("image", "图片"),
                        ],
                        max_length=32,
                        verbose_name="内容类型",
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(default=0, verbose_name="对象 ID"),
                ),
                (
                    "field",
                    models.CharField(blank=True, max_length=32, verbose_name="字段"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="内容地址"
                    ),
                ),
                ("excerpt", models.TextField(verbose_name="内容快照")),
                ("text_hash", models.CharField(max_length=64, verbose_name="内容哈希")),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("none", "无风险"),
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("unknown", "无法判定"),
                        ],
                        default="unknown",
                        max_length=16,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "categories",
                    models.JSONField(blank=True, default=list, verbose_name="命中类别"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="理由")),
                ("quote", models.TextField(blank=True, verbose_name="引用原文")),
                (
                    "model",
                    models.CharField(blank=True, max_length=64, verbose_name="模型"),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="输入 token"),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="输出 token"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待复核"),
                            ("ok", "无问题"),
                            ("handled", "已处置"),
                            ("ignored", "忽略"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="复核时间"
                    ),
                ),
                (
                    "handling_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="处理说明"
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核完成时间"
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="已通知时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="复核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "待复核记录",
                "verbose_name_plural": "待复核记录",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "risk", "created_at"],
                        name="moderation__status_0fdc7d_idx",
                    ),
                    models.Index(
                        fields=["text_hash"], name="moderation__text_ha_c82fc7_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_type", "target_id", "field", "text_hash"),
                        name="unique_moderation_target_text",
                    )
                ],
            },
        ),
    ]
