# Generated by Django 6.0.8 on 2026-09-19 05:00

from django.db import migrations, models


def forget_lfg_notes(apps, schema_editor):
    """Round 066: LFG notes are gone, and so is their review queue entry."""
    apps.get_model("moderation", "ModerationItem").objects.filter(
        target_type="lfg_note"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forget_lfg_notes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="moderationitem",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("nickname", "昵称"),
                    ("team_name", "队名"),
                    ("team_description", "战队简介"),
                    ("application_message", "入队申请留言"),
                    ("article", "文章 / 稿件"),
                    ("tournament_description", "赛事说明"),
                    ("scrim_description", "内战说明"),
                    ("page", "普通页面"),
                    ("image", "图片"),
                ],
                max_length=32,
                verbose_name="内容类型",
            ),
        ),
    ]
