# Generated by Django 6.0.8 on 2026-09-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0002_remove_lfg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderationitem",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("nickname", "昵称"),
                    ("team_name", "队名"),
                    ("team_description", "战队简介"),
                    ("application_message", "入队申请留言"),
                    ("article", "文章 / 稿件"),
                    ("tournament_description", "赛事说明"),
                    ("scrim_description", "内战说明"),
                    ("page", "普通页面"),
                    ("image", "图片"),
                    ("comment", "评论"),
                ],
                max_length=32,
                verbose_name="内容类型",
            ),
        ),
    ]
