# Generated by Django 6.0.8 on 2026-10-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_alter_moderationitem_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationitem',
            name='full_text',
            field=models.TextField(blank=True, verbose_name='整篇正文（待巡查）'),
        ),
    ]
