# Generated by Django 6.0.8 on 2026-10-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_ai_patrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationitem',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='算在这条上的失败次数'),
        ),
        migrations.AddField(
            model_name='moderationitem',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近一次没看成的时间'),
        ),
        migrations.AddField(
            model_name='moderationitem',
            name='last_error',
            field=models.CharField(blank=True, max_length=300, verbose_name='最近一次没看成的原因'),
        ),
    ]
