# Generated by Django 6.0.8 on 2026-09-16 12:26

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="上游名称")),
                (
                    "key_id",
                    models.CharField(max_length=32, unique=True, verbose_name="Key ID"),
                ),
                (
                    "secret",
                    core.fields.EncryptedTextField(
                        help_text="加密存储；验签需要原文，所以不能只存哈希。",
                        verbose_name="Secret",
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(blank=True, default=list, verbose_name="授权范围"),
                ),
                (
                    "allowed_includes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="允许的展开项"
                    ),
                ),
                (
                    "rate_limit_per_minute",
                    models.PositiveIntegerField(default=600, verbose_name="每分钟限流"),
                ),
                (
                    "webhook_url",
                    models.URLField(blank=True, verbose_name="Webhook 地址"),
                ),
                (
                    "webhook_secret",
                    core.fields.EncryptedTextField(
                        blank=True, verbose_name="Webhook 密钥"
                    ),
                ),
                (
                    "webhook_events",
                    models.JSONField(
                        blank=True, default=list, verbose_name="订阅的事件"
                    ),
                ),
                (
                    "webhook_payload_mode",
                    models.CharField(
                        choices=[("thin", "只带 ID"), ("full", "带完整对象")],
                        default="thin",
                        max_length=8,
                        verbose_name="Webhook 内容",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近使用"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="吊销时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "API 客户端",
                "verbose_name_plural": "API 客户端",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ApiRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(max_length=64, verbose_name="请求 ID")),
                ("method", models.CharField(max_length=8, verbose_name="方法")),
                ("path", models.CharField(max_length=500, verbose_name="路径")),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(verbose_name="状态码"),
                ),
                (
                    "error_code",
                    models.CharField(blank=True, max_length=64, verbose_name="错误码"),
                ),
                (
                    "ip",
                    models.CharField(blank=True, max_length=64, verbose_name="来源 IP"),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(default=0, verbose_name="耗时（毫秒）"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_logs",
                        to="integrations.apiclient",
                        verbose_name="客户端",
                    ),
                ),
            ],
            options={
                "verbose_name": "API 调用日志",
                "verbose_name_plural": "API 调用日志",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "-created_at"],
                        name="integration_client__5002d6_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="integration_created_e99cf3_idx"
                    ),
                ],
            },
        ),
    ]
