# Generated by Django 6.0.8 on 2026-09-16 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="事件 ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=64, verbose_name="事件类型"),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="事件内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待投递"),
                            ("succeeded", "已送达"),
                            ("failed", "已失败"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="已尝试次数"
                    ),
                ),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次尝试"
                    ),
                ),
                (
                    "last_status_code",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="最后状态码"
                    ),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="最后错误")),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="送达时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_deliveries",
                        to="integrations.apiclient",
                        verbose_name="客户端",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook 投递",
                "verbose_name_plural": "Webhook 投递",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="integration_status_d4f89b_idx",
                    ),
                    models.Index(
                        fields=["client", "-created_at"],
                        name="integration_client__602dd5_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="integration_created_0e3a14_idx"
                    ),
                ],
            },
        ),
    ]
