# Generated by Django 6.0.8 on 2026-09-25 15:37

from django.db import migrations


def forget_queued_webhook_tasks(apps, schema_editor):
    """Round 067: a queued delivery would fail to import once the code is gone.

    A READY task older than ten minutes makes /healthz report a backlog
    (core/health.py), so the rows leave with the code that owned them.
    """
    DBTaskResult = apps.get_model("django_tasks_database", "DBTaskResult")
    DBTaskResult.objects.filter(task_path__startswith="integrations.").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("django_tasks_database", "__latest__"),
        ("integrations", "0002_webhookdelivery"),
        ("tournaments", "0005_remove_upstream"),
    ]

    operations = [
        migrations.RunPython(forget_queued_webhook_tasks, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="apirequestlog",
            name="integration_client__5002d6_idx",
        ),
        migrations.RemoveIndex(
            model_name="apirequestlog",
            name="integration_created_e99cf3_idx",
        ),
        migrations.RemoveIndex(
            model_name="webhookdelivery",
            name="integration_status_d4f89b_idx",
        ),
        migrations.RemoveIndex(
            model_name="webhookdelivery",
            name="integration_client__602dd5_idx",
        ),
        migrations.RemoveIndex(
            model_name="webhookdelivery",
            name="integration_created_0e3a14_idx",
        ),
        migrations.RemoveField(
            model_name="webhookdelivery",
            name="client",
        ),
        migrations.DeleteModel(
            name="ApiRequestLog",
        ),
        migrations.DeleteModel(
            name="ApiClient",
        ),
        migrations.DeleteModel(
            name="WebhookDelivery",
        ),
    ]
