"""Generate Python full-casefold exceptions to Go's rune lowercasing.
Run with the project's Python on the test machine. No external dependency.
"""
from pathlib import Path
import json
import unicodedata

root = Path(__file__).resolve().parents[3]
rows = []
for point in range(0x110000):
    char = chr(point)
    folded, lower = char.casefold(), char.lower()
    if folded != lower or len(lower) != 1:
        rows.append(f"\t0x{point:X}: {json.dumps(folded, ensure_ascii=True)},")
text = f'''// Code generated by handoff/rounds/274-be-search-session/generate_casefold.py; DO NOT EDIT.
// Python Unicode {unicodedata.unidata_version}: full casefold expansions and non-lowercase folds.
package search

import (
    "strings"
    "unicode"
)

func caseFold(s string) string {{
    var out strings.Builder
    for _, r := range s {{
        if folded, ok := foldExceptions[r]; ok {{ out.WriteString(folded) }} else {{ out.WriteRune(unicode.ToLower(r)) }}
    }}
    return out.String()
}}

var foldExceptions = map[rune]string{{
{chr(10).join(rows)}
}}
'''
(root / "server/internal/search/casefold.go").write_text(text)
print(f"CASEFOLD Unicode {unicodedata.unidata_version}: {len(rows)} exceptions")
