# Generated by Django 6.0.8 on 2026-09-16 07:12

import content.models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0098_apitoken"),
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="名称")),
                (
                    "slug",
                    models.SlugField(
                        max_length=64, unique=True, verbose_name="网址片段"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "allow_submission",
                    models.BooleanField(default=True, verbose_name="开放投稿"),
                ),
            ],
            options={
                "verbose_name": "文章分类",
                "verbose_name_plural": "文章分类",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ArticleIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(blank=True, verbose_name="栏目介绍"),
                ),
            ],
            options={
                "verbose_name": "文章栏目",
            },
            bases=(
                content.models.SeoPageMixin,
                content.models.ReservedSlugMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "首页",
            },
            bases=(content.models.SeoPageMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="StandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("paragraph", 0), ("image", 3), ("quote", 6), ("video", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                    ],
                                    "label": "段落",
                                },
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "图片"},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "图注", "max_length": 200, "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 1), ("caption", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.TextBlock", (), {"label": "引用文字"}),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "出处", "max_length": 100, "required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 4), ("attribution", 5)]],
                                {},
                            ),
                            7: ("content.blocks.VideoBlock", (), {}),
                        },
                        verbose_name="正文",
                    ),
                ),
            ],
            options={
                "verbose_name": "普通页面",
            },
            bases=(
                content.models.SeoPageMixin,
                content.models.ReservedSlugMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                (
                    "summary",
                    models.CharField(blank=True, max_length=200, verbose_name="摘要"),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("paragraph", 0), ("image", 3), ("quote", 6), ("video", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                    ],
                                    "label": "段落",
                                },
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "图片"},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "图注", "max_length": 200, "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 1), ("caption", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.TextBlock", (), {"label": "引用文字"}),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "出处", "max_length": 100, "required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 4), ("attribution", 5)]],
                                {},
                            ),
                            7: ("content.blocks.VideoBlock", (), {}),
                        },
                        verbose_name="正文",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="content.articlecategory",
                        verbose_name="分类",
                    ),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="封面",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章",
            },
            bases=(content.models.SeoPageMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="HomePagePinnedArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="content.articlepage",
                        verbose_name="文章",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_articles",
                        to="content.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "置顶文章",
                "verbose_name_plural": "置顶文章",
                "ordering": ["sort_order"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("page", "article"),
                        name="content_homepinned_unique_article",
                    )
                ],
            },
        ),
    ]
