# Generated by Django 6.0.8 on 2026-09-16 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("tournaments", "0002_alter_tournament_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                help_text="选填。关联后这篇文章会显示在赛事页面上。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="tournaments.tournament",
                verbose_name="关联赛事",
            ),
        ),
    ]
