# Generated by Django 6.0.8 on 2026-09-18 17:21

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_articlepage_tournament"),
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageCarouselItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=60, verbose_name="标题")),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="站内地址以 / 开头，比如 /tournaments/3/；站外地址以 https:// 开头。",
                        max_length=200,
                        verbose_name="或链接地址",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="横图，建议 1600×700 以上。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="图片",
                    ),
                ),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.WAGTAIL_PAGE_MODEL,
                        verbose_name="链接到页面",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carousel_items",
                        to="content.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "焦点图",
                "verbose_name_plural": "焦点图",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
