# Generated by Django 6.0.8 on 2026-09-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_homepage_carousel"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="comments_enabled",
            field=models.BooleanField(
                default=True,
                help_text="关闭后已有评论仍显示，只是不能再发。",
                verbose_name="开放评论",
            ),
        ),
    ]
