# Generated by Django 6.0.8 on 2026-09-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_article_comments"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomePageCarouselItem",
        ),
    ]
