# Generated by Django 6.0.8 on 2026-10-05 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_unnamed_while_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='content.articlecategory', verbose_name='分类'),
        ),
    ]
