# Generated by Django 6.0.8 on 2026-09-19 05:00

import django.db.models.deletion
import django.db.models.functions.text
import members.models
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="名称")),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="简介"),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="不显示的分组不出现在成员展示页上，组里的人仍然在「全部成员」里。",
                        verbose_name="显示",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="数字小的排在前面。", verbose_name="排序"
                    ),
                ),
            ],
            options={
                "verbose_name": "成员分组",
                "verbose_name_plural": "成员分组",
                "ordering": ["sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="members_group_name_ci_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MemberGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="可选，比如「社长」。",
                        max_length=20,
                        verbose_name="职务",
                    ),
                ),
                (
                    "group",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="members.membergroup",
                    ),
                ),
                (
                    "user",
                    members.models.MemberUserField(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="成员",
                    ),
                ),
            ],
            options={
                "verbose_name": "分组成员",
                "verbose_name_plural": "分组成员",
                "ordering": ["sort_order"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "user"), name="members_membership_unique"
                    )
                ],
            },
        ),
    ]
