# Generated by Django 6.0.8 on 2026-10-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membergroupmembership',
            name='title',
            field=models.CharField(blank=True, help_text='可选，比如「社长」。多个职务用顿号分开（「社长、主播」），每个最多 10 字。', max_length=20, verbose_name='职务'),
        ),
    ]
