# Generated by Django 6.0.8 on 2026-10-05 08:36

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_title_help'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membergroup',
            name='members_group_name_ci_unique',
        ),
        migrations.AlterField(
            model_name='membergroup',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='名称'),
        ),
        migrations.AddConstraint(
            model_name='membergroup',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('name', ''), _negated=True), name='members_group_name_ci_unique'),
        ),
    ]
